#!/bin/sh /etc/rc.common

START=16
STOP=13
USE_PROCD=1

start_service() {
    procd_open_instance #启动实例
    procd_set_param command /bin/sh /usr/share/modem/modem_task.sh
    procd_set_param respawn # 定义respawn参数，告知procd当task程序退出后尝试进行重启
    procd_close_instance #关闭实例
}