#!/bin/sh

uci -q get modem.global >/dev/null || uci -q batch <<-EOF >/dev/null
	set modem.global=global
	set modem.global.enable=1
	set modem.global.modem_number=0
	commit modem
EOF

/etc/init.d/modeminit enable
/etc/init.d/modem enable

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@modem[-1]
	add ucitrack modem
	set ucitrack.@modem[-1].init=modem
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
exit 0
